name: wisteria
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1+2

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  simple_icons: ^10.1.3
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#FFFFFF"
  image: assets/splash.png
  fullscreen: true
  branding: assets/branding.png

  android_12:
    color: "#FFFFFF"
    image: assets/splash.png
    branding: assets/branding.png

flutter:
  uses-material-design: true
