// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJwf6dbjwmXDQM_hQeJPcrtzewIM3LOw4',
    appId: '1:107474434419:web:96e6c454329d264ac7ed06',
    messagingSenderId: '107474434419',
    projectId: 'wisteria-f4db4',
    authDomain: 'wisteria-f4db4.firebaseapp.com',
    storageBucket: 'wisteria-f4db4.firebasestorage.app',
    measurementId: 'G-LH9YEKKBGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0g6cAFiQFRr5uEljO7mOj3wq1nsG14Tw',
    appId: '1:107474434419:android:aa74078dec8c59e0c7ed06',
    messagingSenderId: '107474434419',
    projectId: 'wisteria-f4db4',
    storageBucket: 'wisteria-f4db4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8L-67H2U16KcpBmhRty-2BMCQpaj59QQ',
    appId: '1:107474434419:ios:261f0807f267b4d8c7ed06',
    messagingSenderId: '107474434419',
    projectId: 'wisteria-f4db4',
    storageBucket: 'wisteria-f4db4.firebasestorage.app',
    iosBundleId: 'com.example.wisteria',
  );
}
